### PR TITLE
Add missing field to pubspec

### PR DESCRIPTION
**Pull request by jxstxn1**
Addressing Issue #46 

Adding missing values which can occur in a pubspec to the PubSpec Package using extension methods.
I implemented methods which are listed here https://dart.dev/tools/pub/pubspec, but aren't part of the PubSpec package.

Also added a set of test to make sure parsing is working as expected

### CODE REVIEW

**Review by leoafarias — APPROVED** [review]
LGTM

**Comment by leoafarias** [comment]
It seems some tests failed. Let me know if you have it passing on your end, and I can check if anything has changed

**Comment by jxstxn1** [comment]
Fixed the tests from this PR.
I noticed that 3 existing tests are also failing. Should I fix them too?

**Comment by leoafarias** [comment]
It seems the schema had changed. Will have to update it

**Comment by leoafarias** [comment]
@jxstxn1 I had to do a major schema change to this might be a major version bump. Just merged into your fork, let me know if you see any regressions, but now there is a more complete schema

**Pull request merged**
