### PR TITLE
Getting packageScore and packageMetrics no longer throws if a package has not been scanned

### PR DESCRIPTION
**Pull request by Rexios80**
Turns out getPackageMetrics gives 404 as well if the package hasn't been scanned yet

### CODE REVIEW

**Comment by Rexios80** [comment]
Well I fixed the test that I broke, but there's another one that I'm not sure how to fix. It looks like you need to regenerate the list of google dependencies but I can't figure out how to get the generator to run.

**Comment by leoafarias** [comment]
closes #10

**Comment by Rexios80** [comment]
Are you going to make a release on pub.dev for this?

**Comment by Rexios80** [comment]
Oh you already did nice

**Pull request merged**
