### PR TITLE
Refactor paging to be more user friendly

### PR DESCRIPTION
**Pull request by Rexios80**
This PR does the following:
- Adds `PackageTag.topic`
- Replaces `packageNameCompletion()` with the correct implementation (probably a breaking change?)
- Adds `packageNames()` to get all package
- Handle paginated results from `packageNames()` call. The `nextUrl` is currently null but it might not always be
- Adds a `fetchAllPackages ` method so that developers don't have to handle recursive paging themselves if they want all the results for a given query
- Fixes a test

The package metrics test is failing because `packageCreated` and `packageVersionCreated` are no longer present in the returned json. Should we remove these fields? Or make them nullable? That would definitely be a breaking change.

### CODE REVIEW

**Comment by Rexios80** [comment]
Welp this turned into a lot more than I had originally intended, but I need all of this functionality. If you don't want to take this PR I understand since I kind of rewrote the whole codebase, but I think using freezed is much easier to maintain than manually writing all the to/from json, toString, and equality stuff. I tested the packageMetrics endpoint on every package with https://github.com/Rexios80/pub_stats and had no serialization issues. We might want to structure the rest of the pana report with actual objects, but I wasn't sure if that stuff was subject to frequent changes so I just left them as maps.

**Comment by leoafarias** [comment]
@Rexios80 I love using Freezed. The problem with using Freezed on a package for other devs is that can cause dependency conflicts that make it a bit more difficult to keep it up to date., especially if we can achieve the same behavior with just a bit more boilerplate.

Also can you update the readme so I can understand the changes in behavior and the methods? Thank you for your contribution.

**Comment by Rexios80** [comment]
Versioning issues could happen with any dependency. It's not our job to worry about other packages as long as we are keeping ours up to date.

I will work on the readme when I have time.

**Comment by leoafarias** [comment]
I understand but since Freezed is not adding any functionality that we cannot add without it, I believe we can remove it. There are some ide extensions that automatically generate those methods

**Comment by Rexios80** [comment]
I'll just maintain my own fork for now. We can revisit this later if I get time.

**Comment by leoafarias** [comment]
@Rexios80 if you can just point me at the changes you made for the API improvements, or mayhbe just remove the other changes, I can hopefully be able to bring it in a document it!

**Comment by Rexios80** [comment]
The important part is the extra fields from the metrics endpoint

**Pull request closed without merging**
