### PR TITLE
Better recursive paging

### PR DESCRIPTION
**Pull request by Rexios80**
Make recursive paging more flexible

### CODE REVIEW

**Comment by leoafarias** [comment]
@Rexios80 thanks for the PR. could you update the docs with some of these new features, and behaviors?

**Comment by Rexios80** [comment]
This is mostly in preparation for #55 so no behavior changed. The only addition is the `fetchAllPackages` call.

**Comment by Rexios80** [comment]
@leoafarias Do you need anything from me on this?

**Review by leoafarias — APPROVED** [review]
LGTM

**Pull request merged**
